create table if not exists public.student_roster (
    id bigint generated by default as identity primary key,
    name text not null,
    department text,
    student_id text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint student_roster_student_id_format
        check (student_id is null or student_id ~ '^[0-9]{8}$')
);

create unique index if not exists student_roster_name_unique
on public.student_roster (name);

create unique index if not exists student_roster_student_id_unique
on public.student_roster (student_id)
where student_id is not null;

alter table public.student_roster enable row level security;

grant usage on schema public to anon, authenticated;
grant select on public.student_roster to anon, authenticated;

drop policy if exists student_roster_read on public.student_roster;

create policy student_roster_read
on public.student_roster
for select
to anon, authenticated
using (true);

insert into public.student_roster (name, department, student_id) values
    ('김건영', '컴퓨터공학전공', '22611696'),
    ('김건호', '화학과', '22210722'),
    ('김경민', '신소재공학과', '22011090'),
    ('김동하', '컴퓨터학부 정보통신전공', '22312076'),
    ('김동헌', '도시공학과', '22610719'),
    ('김민서', '생명과학과', '22510552'),
    ('김민재', '국어국문학과', '22110010'),
    ('김예지', '컴퓨터공학과', '22611698'),
    ('김은주', '회화과', '22621024'),
    ('김정원', '정치외교학과', '22612194'),
    ('김종우', '미래자동차공학과', '22622050'),
    ('김현영', '의생명공학과', '22620466'),
    ('노현석', '소프트웨어융합전공', '22611919'),
    ('류동윤', '컴퓨터공학과', '21720889'),
    ('박성빈', '컴퓨터학부-소프트웨어융합전공', '22611910'),
    ('박정은', '생명과학과', '22521819'),
    ('박지훈', '기계공학부', '22511083'),
    ('박찬혁', '기계공학과', '22610979'),
    ('박태현', '음악학부 피아노전공', '22121284'),
    ('서재용', '정보통신공학전공', '22511855'),
    ('성재석', '정보통신공학과', '22611828'),
    ('손재현', '컴퓨터공학전공', '22511739'),
    ('안제범', '무역학부', '22112918'),
    ('안혜미', '트랜스아트과', '22521098'),
    ('양채윤', '컴퓨터공학전공', '22511720'),
    ('우지은', '정보통신공학전공', '22212093'),
    ('우효빈', '컴퓨터공학과', '22611773'),
    ('유주호', '행정학과', '22112545'),
    ('이도훈', '컴퓨터공학전공', '22521661'),
    ('이소민', '트랜스아트과', '22621064'),
    ('이승준', '정보통신공학과', '22312050'),
    ('이은진', '컴퓨터공학전공', '22611791'),
    ('이정우', '응용분자요리과학전공', '22601557'),
    ('이준호', '생명과학과', '22510571'),
    ('이준홍', '정보통신전공', '22312042'),
    ('이현호', '심리학과', '22612320'),
    ('임창완', '전공자유선택학부', '22621632'),
    ('장혜원', '트랜스아트과', '22521078'),
    ('정승현', '컴퓨터공학전공', '22611794'),
    ('정인성', '컴퓨터공학과', '22511727'),
    ('정인재', '정보통신공학과', '22611809'),
    ('주성빈', '소프트웨어융합전공', '22611933'),
    ('차태의', '도시공학과', '22310758'),
    ('최은제', '생명과학과', '22510575'),
    ('최현룡', '수학과', '22510378'),
    ('홍주은', '컴퓨터공학과', '22411923'),
    ('조휘제', '시각디자인과', '22621133'),
    ('박우성', '무역학과', '22450150'),
    ('박관규', '가족주거학과', '22020408')
on conflict (name) do update
set department = excluded.department,
    student_id = excluded.student_id,
    updated_at = now();

comment on table public.student_roster is
'Separate roster table for the provided student list.';

comment on column public.student_roster.department is
'Student department or major. Null when not provided in the source list.';

comment on column public.student_roster.student_id is
'Eight-digit student ID. Null when not provided in the source list.';
